export const FETCH_GAMES = "FETCH_GAMES";
export const FETCH_SEARCHED = "FETCH_SEARCHED";
export const FETCH_FAILED ="FETCH_FAILED";
export const REQUEST_FETCH ="REQUEST_FETCH";

export const LOADING_DETAIL = "LOADING_DETAIL"
export const GET_DETAIL = "GET_DETAIL"
